# Generated by Django 3.2.8 on 2022-03-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longName', models.TextField()),
                ('shortName', models.CharField(max_length=200)),
                ('creationDate', models.DateField()),
                ('urlName', models.SlugField()),
                ('dueDate', models.DateField(null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(related_name='_rocketTicket_ticket_dependencies_+', to='rocketTicket.Ticket')),
                ('parentTicket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rocketTicket.ticket')),
            ],
        ),
    ]
