# Generated by Django 4.0.3 on 2022-04-01 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocketTicket', '0003_ticket_children_alter_ticket_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='parentTicket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='rocketTicket.ticket'),
        ),
    ]
