# Generated by Django 4.0.3 on 2022-04-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocketTicket', '0004_alter_ticket_parentticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='childs', to='rocketTicket.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependence', to='rocketTicket.ticket'),
        ),
    ]
